sudo: false
language: ruby
rvm:
  - 2.2.2
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
before_install: gem install bundler -v 1.12.5
install:
  - bundle install --jobs=3 --retry=3
script: rake test
